### ISSUE TITLE
ErrorBuilder does not display when the URL is invalid

### ISSUE THREAD

**Issue by serge66** [onatcipli/meet_network_image#2]
ErrorBuilder does not display when the URL is invalid!
example:
```dart
MeetNetworkImage(
      imageUrl: "https://random.dog/3xx.jpg",
      loadingBuilder: (context) => Center(
        child: CircularProgressIndicator(),
      ),
      errorBuilder: (context, e) => Center(
        child: Text('Error appear!'),
      ),
    )
```

**Comment by serge66** [comment]
`════════ Exception caught by image resource service ════════════════════════════════════════════════
The following _Exception was thrown while resolving an image:
Exception: Could not instantiate image codec.

When the exception was thrown, this was the stack: 
#0      _futurize (dart:ui/painting.dart:4341:5)
#1      instantiateImageCodec (dart:ui/painting.dart:1718:10)
#2      PaintingBinding.instantiateImageCodec (package:flutter/src/painting/binding.dart:88:12)
#3      MemoryImage._loadAsync (package:flutter/src/painting/image_provider.dart:714:18)
#4      MemoryImage.load (package:flutter/src/painting/image_provider.dart:706:14)
...
Image provider: MemoryImage(Uint8List#a31aa, scale: 1.0)
Image configuration: ImageConfiguration(bundle: PlatformAssetBundle#ee1cc(), devicePixelRatio: 3.5, locale: zh_Hans_CN, textDirection: TextDirection.ltr, platform: android)
Image key: MemoryImage(Uint8List#a31aa, scale: 1.0)`
